"""Core modules for Video Montage Linker."""

from .models import (
    BlendCurve,
    BlendMethod,
    FolderType,
    DirectInterpolationMethod,
    TransitionSettings,
    PerTransitionSettings,
    DirectTransitionSettings,
    VideoPreset,
    VIDEO_PRESETS,
    BlendResult,
    TransitionSpec,
    LinkResult,
    SymlinkRecord,
    SessionRecord,
    SymlinkError,
    PathValidationError,
    SourceNotFoundError,
    DestinationError,
    CleanupError,
    DatabaseError,
)
from .database import DatabaseManager
from .blender import ImageBlender, TransitionGenerator, RifeDownloader, PracticalRifeEnv, FilmEnv, OPTICAL_FLOW_PRESETS
from .manager import SymlinkManager
from .video import encode_image_sequence, encode_from_file_list, find_ffmpeg

__all__ = [
    'BlendCurve',
    'BlendMethod',
    'FolderType',
    'DirectInterpolationMethod',
    'TransitionSettings',
    'PerTransitionSettings',
    'DirectTransitionSettings',
    'VideoPreset',
    'VIDEO_PRESETS',
    'BlendResult',
    'TransitionSpec',
    'LinkResult',
    'SymlinkRecord',
    'SessionRecord',
    'SymlinkError',
    'PathValidationError',
    'SourceNotFoundError',
    'DestinationError',
    'CleanupError',
    'DatabaseError',
    'DatabaseManager',
    'ImageBlender',
    'TransitionGenerator',
    'RifeDownloader',
    'PracticalRifeEnv',
    'FilmEnv',
    'SymlinkManager',
    'OPTICAL_FLOW_PRESETS',
    'encode_image_sequence',
    'encode_from_file_list',
    'find_ffmpeg',
]
